### PR TITLE
Auth navbar

### PR DESCRIPTION
**Pull request by rmiyazaki6499**
Updated NavBar to handle Authentication.
Do not merge before PR #40.
https://github.com/jbathel/little-foot-trails/pull/40

### CODE REVIEW

**Comment by rmiyazaki6499** [comment]
@jbathel, I don't know how I did it but there is a random curly brace under the FIND YOUR TRAIL button on the search bar. Could you help me find out how to get rid of it?

**Comment by jbathel** [comment]
Having some internet issues but I will look at this after I get them resolved.

**Comment by jbathel** [comment]
Everything looks good in terms of functionality. I still get two random curly brackets I searched all over for them. One under the find your trail button and one where featured is supposed to render on the home page, which I don't have my featured trail rendering on my home page at all.
I wont be able to work much today. But if you need me to approve something text me, most reliable way to get my attention, and I'll get to it asap.
Screen Shot 2020-03-15 at 7 01 58 AM
Screen Shot 2020-03-15 at 7 02 04 AM

**Comment by rmiyazaki6499** [comment]
@jbathel Yeah, that's the only issue. 
I want to fix it but I also want to merge this branch before @banuaksom starts working because this will be our foundation for our authentication on the frontend.

**Pull request merged**
